### ISSUE TITLE
Warning: a promise was rejected with a non-error: [object String]

### ISSUE THREAD

**Issue by jasonhjohnson** [aurelia-plugins/aurelia-plugins-google-recaptcha#12]
Hi,

I'm getting the following warning a few seconds after the captcha response comes back (full stack at end of this message): `Warning: a promise was rejected with a non-error: [object String]`

It doesn't appear to break anything but I'm wondering if/how I can suppress it. I found what looks to be an identical issue captured here: https://github.com/petkaantonov/bluebird/issues/990.

Any help is appreciated.

Thanks,
Jason

```
Warning: a promise was rejected with a non-error: [object String]    at https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:311:102From previous event:    at new F0 (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:309:60)    at bt.R (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:311:66)    at S2 (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:13:3)    at kC.throw.next (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:12:128)    at https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:375From previous event:    at ut (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:268)    at a0 (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:13:487)    at nU.send (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:311:29)    at https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:495:296From previous event:    at J2.BV.uc (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:495:270)    at A.R (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:312:55)From previous event:    at bt.R (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:312:27)    at S2 (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:13:3)    at kC.throw.next (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:12:128)    at E (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:218)From previous event:    at I (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:351)    at https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:371From previous event:    at ut (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:268)    at a0 (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:13:487)    at gd (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:311:300)    at nU.<anonymous> (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:310:323)    at VI (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:88:58)    at MessagePort.YD (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:87:301)    at MessagePort.Pd.E (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:89:180)
printWarning @ bluebird.js:1564
formatAndLogError @ bluebird.js:1280
warn @ bluebird.js:1175
Promise._warn @ bluebird.js:771
Promise._rejectCallback @ bluebird.js:3256
(anonymous) @ bluebird.js:3271
(anonymous) @ recaptcha__en.js:311
setTimeout (async)
n @ recaptcha__en.js:106
(anonymous) @ recaptcha__en.js:311
S2 @ recaptcha__en.js:13
throw.next @ recaptcha__en.js:12
(anonymous) @ recaptcha__en.js:14
Promise._execute @ bluebird.js:985
Promise._resolveFromExecutor @ bluebird.js:3268
Promise @ bluebird.js:2864
ut @ recaptcha__en.js:14
a0 @ recaptcha__en.js:13
nU.send @ recaptcha__en.js:311
(anonymous) @ recaptcha__en.js:495
tryCatcher @ bluebird.js:5276
Promise._settlePromiseFromHandler @ bluebird.js:3297
Promise._settlePromise @ bluebird.js:3354
Promise._settlePromiseCtx @ bluebird.js:3391
(anonymous) @ bluebird.js:165
(anonymous) @ bluebird.js:4530
attributes (async)
(anonymous) @ bluebird.js:4516
attributes (async)
scheduleToggle @ bluebird.js:4524
schedule @ bluebird.js:4533
Async.invoke @ bluebird.js:164
Promise._then @ bluebird.js:3046
Promise.then @ bluebird.js:2910
BV.uc @ recaptcha__en.js:495
A.R @ recaptcha__en.js:312
Promise._execute @ bluebird.js:985
Promise._resolveFromExecutor @ bluebird.js:3268
Promise @ bluebird.js:2864
(anonymous) @ recaptcha__en.js:312
S2 @ recaptcha__en.js:13
throw.next @ recaptcha__en.js:12
E @ recaptcha__en.js:14
tryCatcher @ bluebird.js:5276
Promise._settlePromiseFromHandler @ bluebird.js:3297
Promise._settlePromise @ bluebird.js:3354
Promise._settlePromise0 @ bluebird.js:3399
Promise._settlePromises @ bluebird.js:3479
(anonymous) @ bluebird.js:175
(anonymous) @ bluebird.js:4530
attributes (async)
(anonymous) @ bluebird.js:4516
attributes (async)
scheduleToggle @ bluebird.js:4524
schedule @ bluebird.js:4533
Async.settlePromises @ bluebird.js:174
Promise._fulfill @ bluebird.js:3425
Promise._resolveCallback @ bluebird.js:3217
(anonymous) @ bluebird.js:3269
I @ recaptcha__en.js:14
tryCatcher @ bluebird.js:5276
Promise._settlePromiseFromHandler @ bluebird.js:3297
Promise._settlePromise @ bluebird.js:3354
Promise._settlePromise0 @ bluebird.js:3399
Promise._settlePromises @ bluebird.js:3479
(anonymous) @ bluebird.js:175
(anonymous) @ bluebird.js:4530
attributes (async)
(anonymous) @ bluebird.js:4516
attributes (async)
scheduleToggle @ bluebird.js:4524
schedule @ bluebird.js:4533
Async.settlePromises @ bluebird.js:174
Promise._fulfill @ bluebird.js:3425
Promise._resolveCallback @ bluebird.js:3217
Promise._settlePromiseFromHandler @ bluebird.js:3309
Promise._settlePromise @ bluebird.js:3354
Promise._settlePromiseCtx @ bluebird.js:3391
(anonymous) @ bluebird.js:165
(anonymous) @ bluebird.js:4530
bluebird.js:1564 Warning: a promise was rejected with a non-error: [object String]    at https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:313:303
printWarning @ bluebird.js:1564
formatAndLogError @ bluebird.js:1280
warn @ bluebird.js:1175
Promise._warn @ bluebird.js:771
Promise._rejectCallback @ bluebird.js:3256
(anonymous) @ bluebird.js:3271
(anonymous) @ recaptcha__en.js:313
setTimeout (async)
n @ recaptcha__en.js:106
(anonymous) @ recaptcha__en.js:313
Promise._execute @ bluebird.js:985
Promise._resolveFromExecutor @ bluebird.js:3268
Promise @ bluebird.js:2864
Dx @ recaptcha__en.js:313
wS @ recaptcha__en.js:497
Kd @ recaptcha__en.js:488
J2 @ recaptcha__en.js:485
ZO @ recaptcha__en.js:491
_callee$ @ aurelia-plugins-google-recaptcha-element.js:103
tryCatch @ runtime.js:65
invoke @ runtime.js:303
prototype.(anonymous function) @ runtime.js:117
step @ aurelia-plugins-google-recaptcha-element.js:18
(anonymous) @ aurelia-plugins-google-recaptcha-element.js:18
tryCatcher @ bluebird.js:5276
Promise._settlePromiseFromHandler @ bluebird.js:3297
Promise._settlePromise @ bluebird.js:3354
Promise._settlePromise0 @ bluebird.js:3399
Promise._settlePromises @ bluebird.js:3479
(anonymous) @ bluebird.js:175
(anonymous) @ bluebird.js:4530
attributes (async)
(anonymous) @ bluebird.js:4516
attributes (async)
scheduleToggle @ bluebird.js:4524
schedule @ bluebird.js:4533
Async.settlePromises @ bluebird.js:174
Promise._fulfill @ bluebird.js:3425
Promise._resolveCallback @ bluebird.js:3217
(anonymous) @ bluebird.js:3269
window.aureliaPluginsGoogleRecaptchaOnLoad @ aurelia-plugins-google-recaptcha-element.js:131
jr @ recaptcha__en.js:486
BV @ recaptcha__en.js:495
(anonymous) @ recaptcha__en.js:500
(anonymous) @ recaptcha__en.js:520
3bluebird.js:1564 Warning: a promise was rejected with a non-error: [object String]    at https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:311:102From previous event:    at new F0 (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:309:60)    at bt.R (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:311:66)    at S2 (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:13:3)    at kC.throw.next (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:12:128)    at https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:375From previous event:    at ut (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:268)    at a0 (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:13:487)    at nU.send (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:311:29)    at https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:495:296From previous event:    at J2.BV.uc (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:495:270)    at A.R (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:312:55)From previous event:    at bt.R (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:312:27)    at S2 (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:13:3)    at kC.throw.next (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:12:128)    at E (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:218)From previous event:    at I (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:351)    at https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:371From previous event:    at ut (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:14:268)    at a0 (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:13:487)    at gd (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:311:300)    at nU.<anonymous> (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:310:323)    at VI (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:88:58)    at MessagePort.YD (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:87:301)    at MessagePort.Pd.E (https://www.gstatic.com/recaptcha/api2/v1539585139095/recaptcha__en.js:89:180)
```

**Comment by annlopez** [comment]
experiencing this as well
